sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
node_js:
  - "7"
  - "7.1"
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "0.12"
  - "iojs"
